-- AlterTable
ALTER TABLE "Bin" DROP CONSTRAINT "Bin_shelfId_fkey";

ALTER TABLE "Bin" ALTER COLUMN "shelfId" DROP NOT NULL;

ALTER TABLE "Bin" ADD CONSTRAINT "Bin_shelfId_fkey" FOREIGN KEY ("shelfId") REFERENCES "Shelf"("id") ON DELETE SET NULL ON UPDATE CASCADE;
